# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 04:15
from __future__ import unicode_literals

import cloudinary.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=80000)),
            ],
        ),
        migrations.CreateModel(
            name='BureauMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('list_position', models.IntegerField()),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=b'image/bureau')),
                ('bio', models.TextField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=4000)),
                ('cc', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True)),
                ('price', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=4000)),
                ('venue', models.CharField(max_length=4000)),
                ('description', models.TextField(blank=True, max_length=80000)),
                ('bwp_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlickR_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('flickr_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('photo_feed', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=1000)),
                ('company', models.CharField(blank=True, max_length=1000)),
                ('mobile_phone', models.CharField(blank=True, max_length=1000)),
                ('home_phone', models.CharField(blank=True, max_length=1000)),
                ('home_fax', models.CharField(blank=True, max_length=1000)),
                ('date_of_birth', models.DateField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=1000)),
                ('if_not_alsace_Reason', models.TextField(blank=True, max_length=4000)),
                ('venue', models.CharField(max_length=1000)),
                ('date_membership_application', models.DateField()),
                ('signature', models.CharField(max_length=1000)),
                ('first_sponsor', models.CharField(blank=True, max_length=1000)),
                ('second_sponsor', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name=b'image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Union_1.Album')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Union_1.Event')),
            ],
        ),
    ]
