# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 01:42
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Union_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickr_album',
            name='flickr_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
