# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 02:14
from __future__ import unicode_literals

import cloudinary.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Union_1', '0002_auto_20160601_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickr_album',
            name='photo_feed',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
